### ISSUE TITLE
[RAID] Netherspite portals dont have lazorbeamz

### ISSUE THREAD

**Issue by plutonium447** [Nolin7777/TBC-Bugtracker#111]
Current behavior:
No lazors appear from the portals in Netherspite's room.

![wowscrnshot_122718_224647](https://user-images.githubusercontent.com/40911527/50482244-6b37b900-0a31-11e9-8cfb-f17441df421c.jpg)

![wowscrnshot_122718_224807](https://user-images.githubusercontent.com/40911527/50482259-7d195c00-0a31-11e9-9ae3-e7f70b8f3cd7.jpg)

![wowscrnshot_122718_224810](https://user-images.githubusercontent.com/40911527/50482290-96baa380-0a31-11e9-9bb2-485a0db8b177.jpg)

Expected behavior:
Lazors should shoot out from the portals so that players know where to stand in order to get hit by them and complete the fight. The lazors should fire from the portals into Netherspite.

Steps to recreate issue
Step 1: Pull Netherspite
Step 2: Gander over the portals
Step 3: See no beautiful lazors

id's:
Netherspite (15689)

Source(s)
https://www.wowdb.com

**Comment by artieau** [comment]
Portals now appear to be working perfectly! please close
