### ISSUE TITLE
Creature targets are not always cleared after leaving combat

### ISSUE THREAD

**Issue by Harrock1** [Nolin7777/TBC-Bugtracker#17]
**Patch:**
2.4.3

**Current behaviour:**
Whilst running back to corpse, enemy mobs will target you and pivot on spot (looks to be attempting to que an ability)

**Expected behaviour:**
Mobs should not see ghost targets.

**Steps to reproduce the problem:**
Step 1: Die by the hand of an enemy in the open world
Step 2: Run to corpse whilst targeting the mob that killed you

**IDs**
nil

**Source**
![wowscrnshot_120718_094151](https://user-images.githubusercontent.com/25610698/49616463-03c7b400-fa05-11e8-8fd1-b28afbbbbb61.jpg)

**Comment by kelno** [comment]
Hopefully fixed with 10456
