### ISSUE TITLE
Mob low health flee

### ISSUE THREAD

**Issue by silumor** [Nolin7777/TBC-Bugtracker#170]
Killing Bonechewer mobs outside Thrallmar npcID 18952

Current behaviour: Once NPC hits low health it begins the flee mechanic, the mob turns and runs at over 100% speed away from the player

Expected behaviour: Mob should turn and move at a reduced speed away from the player.

Steps to reproduce the problem:

Attack mob

Get it to low health

**Comment by kelno** [comment]
Redone here https://github.com/Nolin7777/TBC-Bugtracker/issues/365
