### ISSUE TITLE
Mining only ever returning a single ore

### ISSUE THREAD

**Issue by BrockSamson1** [Nolin7777/TBC-Bugtracker#178]
Patch:
PTR

Current behaviour:
Ore deposits only return a single ore.

Expected behaviour:
In vanilla 2-4 ores per node was the normal

Steps to reproduce the problem:

Mine an ore node

Node before hit
![mining node before hit](https://user-images.githubusercontent.com/46757539/51788650-9d753b80-21d4-11e9-9477-a681a49e5432.jpg)

Node after hit - Note single ore in inventory log
![mining node after hit](https://user-images.githubusercontent.com/46757539/51788662-b1b93880-21d4-11e9-8f08-a964d20b5cb2.jpg)

**Comment by Kaziner** [comment]
Duplicate report; reported on report #89

**Comment by kelno** [comment]
Indeed ty
