### ISSUE TITLE
Mob in wrong locations

### ISSUE THREAD

**Issue by BrockSamson1** [Nolin7777/TBC-Bugtracker#183]
Patch:
PTR

Current behaviour:
Gan arg sapper in honor hold

Expected behaviour:
Gan arg sapper in mine beneath honor hold

Steps to reproduce the problem:
Unsure of cause.
![sapper in wrong place](https://user-images.githubusercontent.com/46757539/51790664-91957380-21ec-11e9-8577-0b804fa610f4.jpg)

**Comment by kelno** [comment]
Fixed with 10441
