### ISSUE TITLE
Unlooted mobs despawning in 60 seconds

### ISSUE THREAD

**Issue by BarrensJerk** [Nolin7777/TBC-Bugtracker#194]
Current behaviour: Unlooted corpses of mobs in hellfire (might be everywhere, have only tried in hellfire) are despawning before being looted after 60 seconds. Mobs observed 17014 Collapsing Voidwalkker, 19527 Vacillating Voidwalker, 19414 Shattered Hand Guard.

Expected Behaviour: Unlooted corpses should persist in game for a lot longer than 60 seconds. Can't find specific references for TBC, but forum quotes from 2010-2012 say 3-5 minutes and DalaranWoW has a github issue covering the same thing
https://github.com/dalaranwow/dalaran-wow/issues/3692
Says 300 seconds for an unlooted normal corpse before decay

**Comment by kelno** [comment]
Fixed with 10444
