### ISSUE TITLE
[Quest] Wing Commander Gryphongar (10344)

### ISSUE THREAD

**Issue by BarrensJerk** [Nolin7777/TBC-Bugtracker#235]
**Current behaviour:**

Walking to finish NPC Wing Commander Gryphongar (20232) doesn't trigger the quest complete, and talking to the NPC doesn't trigger it. There are no gossip options either on the NPC

**Expected behaviour:**

Talking to the NPC 20232 should trigger quest complete so that the quest can be handed in to that NPC

**Steps to reproduce the problem:**

1. Step 1

Pick up quest 10344 from NPC 20234 Runetog Wildhammer

2. Step 2

Walk inside and not be able to hand in quest by proximity to NPC 20232 or pick gossip option to complete quest requirements

**rev. hash/commit:** 
Sunstrider rev. 10269 (c3ddeaeda23a+)

**Comment by kelno** [comment]
Fixed with 10425

**Comment by artieau** [comment]
Does not work on rev. 10440 @kelno

**Comment by kelno** [comment]
Strangely, there is a spell to complete this quest: 35237
Weird weird. Using the spell now.
Fixed with 10450
