### ISSUE TITLE
[Quest] The Lost Supplies

### ISSUE THREAD

**Issue by zemfi** [Nolin7777/TBC-Bugtracker#254]
**Current behaviour:** This quest you are able to start from the quest hand-in NPC, when you shouldn't be able to (you start the quest from an item).

**Expected behaviour:** NPC shouldnt give out the quest, only able to start from the item.

**Steps to reproduce the problem:**
1. Goto NPC 'Quartermaster Lungertz (#5393)' and Accept quest 'The Lost Supplies (#1423)'.
2. Hand-in above quest to the above NPC.

**What should happen:**
1. Loot 'Lost Supplies (#6172)' starting the quest from 'Scattered Crate (#28604)'.
2. Hand-in quest to the above NPC.

rev. 10357

**Comment by kelno** [comment]
Fixed by 10423

**Comment by artieau** [comment]
Working rev. 10440

**Comment by kelno** [comment]
Thanks
