### ISSUE TITLE
Shared loot/currency as solo

### ISSUE THREAD

**Issue by zemfi** [Nolin7777/TBC-Bugtracker#256]
**Current behaviour:** Killing mobs and looting them is showing the loot/money as shared when you are the only player/solo.

**Expected behaviour:** Should be showing: 'You loot.. etc" not 'Your share of the loot is.. etc" after.

**Steps to reproduce the problem:**

1. Kill and npc that drops currency
2. Check the chat log.

![tbc_currency](https://user-images.githubusercontent.com/46832429/52173553-ce5bfe80-27da-11e9-9419-44ec0e1077ce.jpg)

.rev 10357

**Comment by kelno** [comment]
Fixed with 10559
