### ISSUE TITLE
When hitting "Complete Quest" button; quest window does not close

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#27]
Patch:
2.4.3

Current behavior:
When I click "Complete Quest" button the quest window does not close (the quest does complete though). I need to manually hit the escape key to close the window to proceed.

Expected behaviour:
When I hit "Complete Quest" the window should close

Steps to reproduce the problem:
Step 1: Finish a quest and attempt to hand in

![report 009](https://user-images.githubusercontent.com/45530324/49696217-8f526800-fbf2-11e8-91a1-b5bdfae28ef1.JPG)

**Comment by artieau** [comment]
Appears fixed now in rev: 10402
