### ISSUE TITLE
[Kara] Attumen the Huntsman

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#288]
**Current behaviour:**

When either Attumen or Mightnight reach 0%, the combined boss spawns.

**Expected behaviour:**

The combined boss should spawn when one of the two above reach 25% HP.

https://wow.gamepedia.com/Attumen_the_Huntsman

**Steps to reproduce the problem:**

1. Zerg Midnight to dead
2. Boss spawn when it die

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
Could not reproduce this one, either by dpsing midgnight or attumen.
Need retest or better reproduce steps, could be happening on very specific conditions.
But the script around this seems pretty simple so I have no idea.

**Comment by artieau** [comment]
Yeh its fine now, probably just GM commands messed it up.
