### ISSUE TITLE
[Kara] Moroes

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#289]
**Current behaviour:**

When Moroes vanishes, he is vanished for only a few seconds.
When he returns, he is at the position he vanished from (at the tank target).

**Expected behaviour:**

Moroes is usually vanished for a longer period of time (length source needed).
When he returns, he is supposed to start from the Garrote target and run back to the tank (highest threat)

**Steps to reproduce the problem:**

1. Pull Moroes
2. Wait 30sec for Vanish
3. Observe duration he is gone for and returns to fight at tank

**rev. hash/commit:** 

REV: 10421

**Comment by Jerrythemagicdog** [comment]
"    * Prenerf Moroes Vanish Phase 8sec not 12sec, from Videos." 

https://github.com/Looking4Group/L4G_Core/issues/637

**Comment by kelno** [comment]
For the first one, what is "only a few seconds" exactly?
I think the second one is a non issue.

**Comment by kelno** [comment]
Okay it's currently 5000 in the script

**Comment by artieau** [comment]
If going pre-nerf, then should have his return from vanish correct.
4 sec difference during vanish + instantly back at tank is much less time for raid to adjust etc.
My thoughts anyway.
