### ISSUE TITLE
[Kara] Opera - Romeo and Juliet

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#290]
**Current behaviour:**

When Juliet first dies, and while waiting for Romeo to spawn, her corpse follows the players around.
When the boss is defeated, loot is only available from Juliet and not Romeo (as his corpse disappears)

**Expected behaviour:**

Juliet corpse should not follow players.
Both Romeo and Juliet should should be visible to loot and provide an item each.

**Steps to reproduce the problem:**

1. Kill Juliet in Phase 1
2. Watch her corpse follow you and  haunt you
3. Kill both of the bastards and only get half a reward :(

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
Fixed with 10430

**Comment by kelno** [comment]
Romulo dying fixed with 10431
