### ISSUE TITLE
[Blood Furnace] - Fel Orc Neophyte

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#298]
**Current behaviour:**

Fel Orc Neophyte # 17429 in the room of boss Broggok can not be attacked and will remain kneeling while moving and attacking players.

**Expected behaviour:**

Mob should be attackable, it should stand up when engaged.

**Steps to reproduce the problem:**

1. Aggro pack before boss
2. Try attack 17429
3. Cant

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
Database for the non attackable part.
The "remain kneeling" is probably a core issue.

**Comment by zemfi** [comment]
Would be related to this aswell: #266

**Comment by kelno** [comment]
Yeah totally is.
I'm keeping this issue only for the "non attackable" part.

**Comment by Jerrythemagicdog** [comment]
Fixed with:
https://github.com/kelno/sunstrider-scripts/commit/e9e63612b79ce0791e341212db5848a88b070775
https://github.com/kelno/sunstrider-scripts/commit/713367c98e0d317d934c18bf6ba017ec430fd65c
