### ISSUE TITLE
[Blood Furnace] Broggok

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#299]
**Current behaviour:**

The lever before Broggok # 17380 to start the encounter can not be clicked on.

**Expected behaviour:**

It should be interact-able by players to start the boss encounter.

**Steps to reproduce the problem:**

1. Try click the lever
2. Cant!

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
Fixed
