### ISSUE TITLE
[Old Hillsbrad] Durnholde Rifleman

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#300]
**Current behaviour:**

Durnholde Rifleman # 17820
Mob's ability multishot hits very hard - see previous tickets about similar issue with archers in Ramparts which was fixed.
Hits about 3-4k each.

**Expected behaviour:**

Should hit a lot less, exact numbers will need source.

**Steps to reproduce the problem:**

1. Engage Rifleman
2. Cry in death

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
Same as https://github.com/Nolin7777/TBC-Bugtracker/issues/56

**Comment by SUN-Leekie** [comment]
I slightly nerfed it and that should be correct.
Nerfed in 10444.
