### ISSUE TITLE
[Old Hillsbrad] - Incendiary boxes

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#301]
**Current behaviour:**

The box which players use ItemID#25853 on can be used multiple times by players, meaning players only need to clear 1 house instead of all 5.

**Expected behaviour:**

Each box should only have 1 use.

**Steps to reproduce the problem:**

1. Use itemID#25853 on box
2. USe it again 4 more times
3. Boss spawns

**rev. hash/commit:** 

Rev: 10421

**Comment by SUN-Leekie** [comment]
Fixed in 10444.
However the state will not be persistent after a crash. To be fixed when the whole instance is redone.

**Comment by kelno** [comment]
The state is now persistent after a crash!
