### ISSUE TITLE
[NPC] Lord Klaq

### ISSUE THREAD

**Issue by zemfi** [Nolin7777/TBC-Bugtracker#303]
**Current behaviour:**

Engaging Lord Klaq (#18282) he has the Thorns Buff (#35361) but checking the combat log, nothing happened to the player (attacking player should be taking damage). Check pic below.

**Expected behaviour:**

Attacking player gets damage from the thorns buff from the NPC.

**Steps to reproduce the problem:**

1. Engage the NPC, observe.

![tbc_lordklaq](https://user-images.githubusercontent.com/46832429/52534021-17d6bb80-2d90-11e9-8f25-efe2e2f1f209.jpg)

.rev 10421

**Comment by kelno** [comment]
Might be some missing data in spell_proc table
