### ISSUE TITLE
[TRACKING] Find Minerals & Find Herbs - Broken

### ISSUE THREAD

**Issue by zemfi** [Nolin7777/TBC-Bugtracker#305]
**Current behaviour:**

Both the Find Minerals (#2580) & Find Herbs (#2383); are now broken, and were **previously** working.

**Expected behaviour:**

Enable tracking of either of the above, find a node and observe the mini-map (a yellow button/marker should appear above the node)

**Steps to reproduce the problem:**

1. Check Expected behaviour
2. No button/marker on the mini-map (regression?)

![tbc_track1](https://user-images.githubusercontent.com/46832429/52543283-b26ce400-2dfc-11e9-9374-a566cb748d91.jpg)
![tbc_track2](https://user-images.githubusercontent.com/46832429/52543284-b3057a80-2dfc-11e9-986a-7fbb29997234.jpg)

.rev 10422

**Comment by kelno** [comment]
Probably fixed with 10424, need test

**Comment by kelno** [comment]
Fixed with 10424

**Comment by artieau** [comment]
Working now rev. 10440

**Comment by kelno** [comment]
Thanks
