### ISSUE TITLE
[Quest] Scalding Mornbrew Delivery

### ISSUE THREAD

**Issue by Tamosheik** [Nolin7777/TBC-Bugtracker#306]
**Current behaviour:**
Upon accepting the quest [Scalding Mornbrew Delivery, Quest.ID# 3364], the quest is automatically completed.

**Expected behaviour:**
A 5 minute timer should start, the quest should be able to be turned in at [Durnan Furcutter, NPC.ID# 836]. The quest should fail if not turned in within the 5 minute timer.

**Steps to reproduce the problem:**
1. Accept Scalding Mornbrew Delivery from [Nori Pridedrift, NPC.ID# 12738]
2. The quest is now complete

**rev. hash/commit:** 
Sunstrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Can this just be that the quest is indeed automatically completed but still gets failed if timer expires?
If not, what should be retail behavior? The quest should show as completed only when you talk to the turn in npc?

**Comment by Tamosheik** [comment]
The quest is automatically turned in and the mug is destroyed, as soon as it is accepted.

**Comment by kelno** [comment]
Okay thanks

**Comment by kelno** [comment]
Fixed with 10437

**Comment by artieau** [comment]
Quest now keeps the mug. Now fails after 5minutes. Still 'auto completes' but that is normal behaviour for turn in quests
