### ISSUE TITLE
[Quest] Ammo for Rumbleshot

### ISSUE THREAD

**Issue by Tamosheik** [Nolin7777/TBC-Bugtracker#307]
**Current behaviour:**
The quest [Ammo for Rumbleshot, Quest.ID# 5541] starts from [Hegnar Rumbleshot, NPC.ID# 1243] instead of [Loslor Rudge, NPC.ID# 1694].

**Expected behaviour:**
The quest should begin at Loslor Rudge, and end at Hegnar Rumbleshot

**rev. hash/commit:**
Sunstrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Fixed with 10424
