### ISSUE TITLE
[Quest] Bitter Rivals

### ISSUE THREAD

**Issue by Tamosheik** [Nolin7777/TBC-Bugtracker#310]
**Current behaviour:**
The quest [Bitter Rivals, Quest.ID# 310] cannot be completed because it requires interaction with an object in the game world. Many game objects currently appear to be un-interactable

**Expected behaviour:**
The object [Unguarded Thunder Ale Barrel, Obj.ID# 270] should be the completion point for the quest, however it does not show the ? icon, nor can it be clicked. See screenshot.

**rev. hash/commit:**
Sunstrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

![image](https://user-images.githubusercontent.com/40758487/52546562-282c7c00-2e0c-11e9-9b14-0738cf6c2a71.png)

**Comment by kelno** [comment]
Probably fixed with 10424,

**Comment by Jerrythemagicdog** [comment]
Related issue: https://github.com/ValorenWoW/sunstrider-issues/issues/168

**Comment by artieau** [comment]
Barrel can be clicked on, but lead up mini-quest is missing.
Should talk to NPC # 1373 and he should have Blue question mark.
He requires 1 x ItemID # 2686 to complete his Blue mini-quest # 308

**Comment by kelno** [comment]
Okay, I'll keep the [ValorenWoW/sunstrider-issues#168](https://github.com/ValorenWoW/sunstrider-issues/issues/168)
as it is more detailed
