### ISSUE TITLE
[Talent] Druid Brambles not working

### ISSUE THREAD

**Issue by Smudgee** [Nolin7777/TBC-Bugtracker#315]
**Current behaviour:**

Druid Balance Talent "Brambles 3/3" Does not work. - 
Spell ID 26992 (thorns) 
Spell ID 26989 (entangling roots) 

**Expected behaviour:**
"Increases damage caused by your Thorns and Entangling Roots spells by 25%"
Tested Thorns without talent at 80dmg per hit, did not hit any harder with talent. 

**Steps to reproduce the problem:**

```
1. Spec into talent

2. Get hit

3. Shrug cause its just thorns. 
```

**rev. hash/commit:**
REV: 10421

**Comment by Jerrythemagicdog** [comment]
Fixed with https://github.com/kelno/sunstrider-core/commit/14ba65df19a8da20bcb88ea7bcb6d34d8bab9621

Change will go live with next update.
