### ISSUE TITLE
[Quest] The Lost Pilot

### ISSUE THREAD

**Issue by Tamosheik** [Nolin7777/TBC-Bugtracker#317]
**Current behaviour:**
The quest [Bitter Rivals, Quest.ID# 419] cannot be completed because it requires interaction with an object in the game world. Many game objects currently appear to be un-interactable

**Expected behaviour:**
The object [A Dwarven Corpse, Obj.ID# 2059] should be the completion point for the quest, however it can not be clicked.

**rev. hash/commit:**
Sunstrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Probably fixed with 10424,

**Comment by artieau** [comment]
Barrel can be clicked on, but lead up mini-quest is missing.
Should talk to NPC # 1373 and he should have Blue question mark.
He requires 1 x ItemID # 2686 to complete his Blue mini-quest # 308

**Comment by artieau** [comment]
Now working in rev. 10440
