### ISSUE TITLE
[Quest] Alicia's Poem 11451

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#318]
**Current behaviour:**

Quest is available both from Alicia#24729 and from end NPC of quest Caylee Dak#24727

**Expected behaviour:**

Quest should only be available from Alicia#24729

**Steps to reproduce the problem:**

1. Go to Caylee Dak#24727 in Shatt
2. Pickup quest
3. Turn it in on the spot...

**rev. hash/commit:** 

REV: 10422

**Comment by kelno** [comment]
Fixed by 10423

**Comment by artieau** [comment]
Working now rev. 10440
