### ISSUE TITLE
[Item] Libram of Mending incorrect behaviour

### ISSUE THREAD

**Issue by plutonium447** [Nolin7777/TBC-Bugtracker#319]
**Current behaviour:**
Performing any spell with the libram equipped will trigger the effect of the item.
![screenshot from 2019-02-12 22-25-47](https://user-images.githubusercontent.com/40911527/52636139-809c7000-2f17-11e9-8254-1a60b65b30be.png)

**Expected behaviour:**
Only casting Holy Light should trigger the effect of the item.

**Steps to reproduce the problem:**

1. Be a paladin.
2. Equip Libram of Mending
3. Cast a spell like Seal of Light, or Flash of Light
4. the effect will trigger

**rev. hash/commit:** 
![screenshot from 2019-02-12 22-27-55](https://user-images.githubusercontent.com/40911527/52635962-079d1880-2f17-11e9-8905-65afd448a849.png)

**id's:**
[item] Libram of Mending (33502) http://db.hellfire-tbc.com/?item=33502
[effect] Grace of the Naaru (43742) http://db.hellfire-tbc.com/?spell=43742

**Comment by Jerrythemagicdog** [comment]
Fixed with https://github.com/kelno/sunstrider-core/commit/14ba65df19a8da20bcb88ea7bcb6d34d8bab9621

Change will be live with next update.
