### ISSUE TITLE
Arcatraz Final boss server crash

### ISSUE THREAD

**Issue by qoth** [Nolin7777/TBC-Bugtracker#320]
**Current behaviour: Final boss (Warden Mellichar [ID :20904]) of The Arcatraz spawns first mini boss but crashes the server before summoning Millhouse Manastorm [ID: 20977] (The one friendly mob that spawns on this fight that helps you)**

**Expected behaviour: Millhouse Manastorm [ID: 20977] should spawn without a server crash **

**Steps to reproduce the problem:**

1. Step 1 : Begin boss fight by walking up to Warden Mellichar [ID :20904]
2. Step 2 : Defeat first mini boss
3. Step 3 : Wait as Millhouse Manastorm [ID: 20977] should be summoned, but server will crash.

Suntrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Fixed with 10442
