### ISSUE TITLE
[Item] Set bonus not applying

### ISSUE THREAD

**Issue by artieau** [Nolin7777/TBC-Bugtracker#325]
**Current behaviour:**

Shaman Elemental Tier6 Itemset # 684
2 Piece bonus (Spell effect # 38443) does not grant any benefit to the player when criteria are met.

**Expected behaviour:**

The Spell effect should grant its effect when criteria are met (1 of each totem type placed down)

**Steps to reproduce the problem:**

1. Equip at least 2 pieces of Item set 684
2. Place one of each totem type
3. No change in any stats or damage etc

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52708037-3e3d6680-2fdd-11e9-9d6f-386fe75bcbd3.png)

kel hi

**Comment by kelno** [comment]
Fixed with 10464

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/b087aa4dcce176a6a5d919288cafc2fd585bc3ac
