### ISSUE TITLE
Trinket "Heart of Wyrmthalak" (22321) currently backfiring onto player

### ISSUE THREAD

**Issue by Harrock1** [Nolin7777/TBC-Bugtracker#35]
**Patch:**
2.4.3

**Current behaviour:**
Trinkets can backfire and do damage to the caster despite it being an on attack effect. Trinkets still currently hit enemy targets, but somehow also hit the player weilding them

**Expected behaviour:**
On attack effects should apply to the target, unless specified in the item tooltip

**Steps to reproduce the problem:**
Step 1: Equip 'on attack' trinket
Step 2: Attack any mob until proc is shown

**IDs**
[Item] Heart of Wyrmthalak (22321)

**Source**

![wyrmtrink](https://user-images.githubusercontent.com/25610698/49770243-af3f7400-fd37-11e8-87be-992518663f0e.JPG)

**Comment by artieau** [comment]
Seems fixed now on rev: 10402
