### ISSUE TITLE
Fel overseer not patroling

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#354]
**Current behaviour:**

Fel overseer not paroling

**Expected behaviour:**

This specific Fel overseer should patrol

**Steps to reproduce the problem:**

1. Go this to particuar fel overseer and note he isnt moving

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

(Pictured dead in top left; he never left that position the entire time)
![image](https://user-images.githubusercontent.com/45530324/52715850-34b9fb80-2fe9-11e9-8a3f-92243257d96e.png)

https://db.excalibur.ws/?npc=18796

**Comment by Jerrythemagicdog** [comment]
There are already 3 Fel Overseers patroling in that area, believe this one is fine.

**Comment by Kaziner** [comment]
https://www.youtube.com/watch?v=tedQDIjXU6U

13:52 you can see the Fel overseer patrols out of the hallway
