### ISSUE TITLE
Ambassador Hellmaw doesn't patrol the room when released

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#355]
**Current behaviour:**

Ambassador Hellmaw

**Expected behaviour:**

He should do a lap of the room; rookie groups will accidently face pull him while still low on mana/hp from killing the last mobs in the room

**Steps to reproduce the problem:**

1. Release Ambassador Hellmaw (kill all mobs in the room)
2. Watch him not do a lap of the room

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/45530324/52715970-76e33d00-2fe9-11e9-80fb-070421bce80d.png)

https://db.excalibur.ws/?npc=18731

**Comment by Jerrythemagicdog** [comment]
Fixed in 10441
