### ISSUE TITLE
[Mage] - Fire vulnerability debuff from scorch - Not stacking with other mages.

### ISSUE THREAD

**Issue by Cheelout** [Nolin7777/TBC-Bugtracker#370]
*Current behaviour:**

Spells:
Scorch - 2948
Fire vulnerability - 22959

Fire Vulnerability is not stacking with other mages stacks
If stack count = 1 - New mage will over write old mages stack
If stack count > 1 - Does not apply another stack or refresh duration
Only the original mage can increase stacks

**Expected behaviour:**

All mages scorch adds a fire vulnerability stack and refreshes duration 

**Steps to reproduce the problem:**

1. Step 1 - have 2 mages in a group with 3/3 Improved Scorch
2. Step 2 - mage 1 Casts scorch - Stack applied
3. Step 3 - Mage 2 casts scorch - Stack does not increase and reapplies new mages debuff

Server Revision: 10530

Tested on the following mobs:
Lair Brute - 19389
Gruul The Dragonkiller - 19044
High King Maulgar - 18831

**Comment by kelno** [comment]
Please use the new bugtracker https://github.com/ValorenWoW/sunstrider-issues/

**Comment by kelno** [comment]
https://github.com/ValorenWoW/sunstrider-issues/issues/654
