### ISSUE TITLE
[Threat] - Prot Warrior / Feral Druid / Prot Paladin - Threat generation seems very low

### ISSUE THREAD

**Issue by Cheelout** [Nolin7777/TBC-Bugtracker#371]
Sorry this report is going to be pretty generic.

We have noticed in testing that threat generated by abilities from Warriors / Druids / Paladins seems to be low.

During our raid testing it was very easy to pull aggro off a tank who had been tanking the mob for some times without anyone attacking it. (Talking minutes)

**Comment by kelno** [comment]
I can give you a `.debug threat` command to facilitate testing regarding to that.

**Comment by kelno** [comment]
Damn. This is the wrong BugTracker, can you use the other one instead?
