### ISSUE TITLE
Druid: shifting to Cat form enables "track Humanoids"

### ISSUE THREAD

**Issue by mrqiksta** [Nolin7777/TBC-Bugtracker#372]
**Current behaviour:**

Druid: shifting to Cat form enables "track Humanoids", switching to any other form clears tracking to "track nothing"

**Expected behaviour:**

Shifting to cat form should not change what the druid is tracking on the minimap

**Steps to reproduce the problem:**

1. Shift to catform, check minimap tracking has changed
2. Shift out of catform, check minimap tracking is "nothing"

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static) 

NOTES: 
- Please don't be shy on the details and context, screenshots and videos are VERY welcome
- Include the ID for game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, skills related to this issue.

**Comment by kelno** [comment]
This bugtracker is deprecated, use this one: https://github.com/thebarrensissues/Issues
