### ISSUE TITLE
Underground worms (that have little rocks popping out of the surface) are not surfacing

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#50]
Current behavior:
The worms do not aggro and come out to be attacked/attack me but they still put me into combat

Expected behaviour:
They should burst out of the ground and commence combat

Steps to reproduce the problem:

Step 1: Go stand ontop of a worm and watch it not come out
![wowscrnshot_121718_171957](https://user-images.githubusercontent.com/45530324/50072215-25ecdd80-0220-11e9-9be3-23e1ab6f8759.jpg)

**Comment by kelno** [comment]
Fixed with 10444
