### ISSUE TITLE
NPC in quest "The road to Falcon Watch" does not aggro mobs as she runs to Falcon Watch

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#51]
Current behavior:
The NPC doesnt aggro anything; nothing spawns at what appeared to be scripted events for us to be ambushed

Expected behaviour:
The mobs should attack her and mobs should spawn in during the event

Steps to reproduce the problem:

Step 1: Start The Road of Falcon Watch quest
Step 2 : Watch her run past mobs
![report 015](https://user-images.githubusercontent.com/45530324/50072308-79f7c200-0220-11e9-816b-f0e4f86b0a59.JPG)

**Comment by artieau** [comment]
Fixed, can close
