### ISSUE TITLE
Bleeding Hollow Archer's Multi-shot hits too hard

### ISSUE THREAD

**Issue by Kaziner** [Nolin7777/TBC-Bugtracker#56]
Current behavior:

Currently the bleeding hollow archer's multishot is hitting for 1.8k damage as a level 61 vs a level 70

Expected behavior:

It should hit significantly less (wiped as 70's in a 60 dung)

Step 1: Get attached by a bleeding hollow archer's multishot
![wowscrnshot_121718_195126](https://user-images.githubusercontent.com/45530324/50079437-5c812300-0235-11e9-8136-67b1c5f87994.jpg)

**Comment by artieau** [comment]
Rev: 10402
They do hit very hard, but doesnt appear to be incorrect anymore. can close
